apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote
  labels:
    app: azure-vote
  namespace: devhub-e2e-test-id-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote
  template:
    metadata:
      labels:
        app: azure-vote
    spec:
      containers:
        - name: azure-vote
          image: devhube2eqngbyhlu.azurecr.io/kubeimage:latest
          ports:
            - containerPort: 8080